# Generated by Django 4.2.28 on 2026-03-19 02:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skillsessions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="duration",
        ),
        migrations.AddField(
            model_name="session",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                default=60, validators=[django.core.validators.MinValueValidator(5)]
            ),
            preserve_default=False,
        ),
    ]
